name: Python linter

on:
  push:
    branches:
      - master
      - 'release/**'
    paths:
      - python/**
      - pyproject.toml
      - .github/workflows/**
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - python/**
      - pyproject.toml
      - reports/*.qmd
      - .github/workflows/**
      - uv.lock

permissions:
  contents: read
  checks: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: astral-sh/ruff-action@v3.5.1
        with:
          src: "./python/pdstools"
