name: Python linter

on:
  push:
    branches:
      - master
      - 'release/**'
    paths:
      - python/**
      - pyproject.toml
      - .github/workflows/**
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - python/**
      - pyproject.toml
      - .github/workflows/**

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/ruff-action@v3.5.1
        with:
          src: "./python"
          args: --output-formatting-github
