#!/bin/bash

# Location of the GIT checkout of the CDH tools

cdhtools="~/Documents/pega/cdh-datascientist-tools"

# Location of the input data

modeldata="$cdhtools/r/models.csv"
predictordata="$cdhtools/r/predictors.csv"

# Prefix of the generated reports and name of file with the model ID's. 
# You don't provide this file, this is generated by the model overview notebook.

nameprefix="CDHSample"
modellist="cdhsample-modellist.txt"

# Location of the notebooks (unless copied/modified these defaults should be fine)

modeloverviewnotebook="$cdhtools/offlinereports/adaptivemodeloverview.Rmd"
modelreportnotebook="$cdhtools/offlinereports/modelreport.Rmd"

# Run the model overview notebook

R -e "rmarkdown::render('$modeloverviewnotebook',params = list(modelfile='$modeldata', modellist='`pwd`/$modellist', predictordatafile='$predictordata'), output_file='`pwd`/$nameprefix\ Model Overview with Predictor Overview.html')"

while read p; do
modelID="$(cut -d';' -f1 <<<"$p")"
modelName="$(cut -d';' -f2 <<<"$p")"

R -e "rmarkdown::render('$modelreportnotebook',params = list(predictordatafile='$predictordata', modeldescription='$modelName', modelid='$modelID'), output_file='`pwd`/$nameprefix Model Report $modelName.html')"

done <$modellist
