- Predictors:
    maskPredictorNames: Y
    maskPredictorValues: Y
    ExcludePredictors: Decision_DecisionTime,Decision_OutcomeTime
- ContextKeys:
    maskContextKeyNames: Y
    maskContextKeyValues: Y
    ContextKeyPredictors: Context_*
- IHPredictors:
    maskIHPredictorNames: y
    maskIHPredictorValues: y
    IHPredictors: IH_*
- OutcomeColumn:
    maskOutcomeName: Y
    maskOutcomeValues: Y
    OutcomeAccepts: Accepted,Accept
    OutcomeRejects: Rejected
    OutcomeColumn: Decision_Outcome
- FilePaths:
    useDatamart: n
    datamartFolder: /Users/hasss/dev/anonymizer/datamart
    outputFolder: /Users/hasss/dev/anonymizer/output
    hdrFolder: /Users/hasss/dev/anonymizer/data
    outputFormat: ndjson