- Predictors:
    maskPredictorNames: Y
    maskPredictorValues: Y
    specialPredictors: Decision_DecisionTime,Decision_OutcomeTime
- ContextKeys:
    maskContextKeyNames: Y
    maskContextKeyValues: Y
    contextKeyPredictors: Context_*
- IHPredictors:
    maskIHPredictorNames: y
    maskIHPredictorValues: y
    ihPredictors: IH_*
- OutcomeColumn:
    maskOutcomeName: Y
    maskOutcomeValues: Y
    outcomeAccepts: Accepted,Accept
    outcomeRejects: Rejected
    outcomeColumn: Decision_Outcome
- FilePaths:
    useDatamart: n
    datamartFolder: /Users/hasss/dev/anonymizer/datamart
    outputFolder: /Users/hasss/dev/anonymizer/output
    hdrFolder: /Users/hasss/dev/anonymizer/data
    outputFormat: ndjson