#!/bin/bash

# Build off-line model reports from DMSample data. The predictor and model
# data is in CSV files that can be generated by exporting the two data sets
# then running the R script in this same folder. Alternatively they can be
# exported directly from the database.

modeloverviewnotebook="../healthcheck.Rmd"
modelreportnotebook="../modelreport.Rmd"

modeldata="`pwd`/models.csv"
predbinning="`pwd`/predbinning.csv"

nameprefix="DMSample"
modellist="modellist.txt"

# Models overview - first one just uses the model data, second one also uses the predictor binning data

R -e "rmarkdown::render('$modeloverviewnotebook',params = list(modelfile='$modeldata', modellist='`pwd`/$modellist'), output_file='`pwd`/$nameprefix\ Model Overview.html')"

R -e "rmarkdown::render('$modeloverviewnotebook',params = list(modelfile='$modeldata', modellist='`pwd`/$modellist', predictordatafile='$predbinning'), output_file='`pwd`/$nameprefix\ Model Overview with Predictor Overview.html')"

# Individual model reports

while read p; do
modelID="$(cut -d';' -f1 <<<"$p")"
modelName="$(cut -d';' -f2 <<<"$p")"

R -e "rmarkdown::render('$modelreportnotebook',params = list(predictordatafile='$predbinning', modeldescription='$modelName', modelid='$modelID'), output_file='`pwd`/$nameprefix Model Report $modelName.html')"

done <$modellist
