#!/bin/bash

# Location of the GIT checkout of the Pega Data Scientist tools

pdstools="~/Documents/pega/pega-datascientist-tools"

# Location of the input data

modeldata="~/Downloads/models.csv"
predictordata="~/Downloads/predictors.csv"

# Prefix of the generated reports and name of file with the model ID's. 
# You don't provide this file, this is generated by the model overview notebook.

title="CDHSample"
modellist="cdhsample-modellist.txt"

# Location of the notebooks (unless copied/modified these defaults should be fine)

modeloverviewnotebook="$pdstools/examples/datamart/healthcheck.Rmd"
modelreportnotebook="$pdstools/examples/datamart/modelreport.Rmd"

# Run the model overview notebook

R -e "rmarkdown::render('$modeloverviewnotebook',params = list(modelfile='$modeldata', modellist='`pwd`/$modellist', predictordatafile='$predictordata', title='$title', subtitle='ADM Datamart Health Check'), output_file='`pwd`/$title\ Adaptive Model Overview.html')"

while read p; do
modelID="$(cut -d';' -f1 <<<"$p")"
modelName="$(cut -d';' -f2 <<<"$p")"

R -e "rmarkdown::render('$modelreportnotebook',params = list(predictordatafile='$predictordata', modeldescription='$modelName', modelid='$modelID', title='$title', modeldescription='$modelName'), output_file='`pwd`/$title Model Report $modelName.html')"

done <$modellist
