name: Check Python docs

on:
  pull_request:
    paths:
      - python/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build-docs:
    runs-on: ubuntu-latest
    name: Check Python docs
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: pip

      - name: Install dependencies
        working-directory: python
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r docs/docs-requirements.txt
          sudo apt-get update
          sudo apt-get install -y pandoc
          sudo apt install -y graphviz


      - name: Build Python documentation
        working-directory: python/docs
        run: make html
