name: Check Python docs

on:
  pull_request:
    paths:
      - python/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build-docs:
    runs-on: ubuntu-latest
    name: Check Python docs
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install 3.11

      - name: Enable caching
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: |
            **/pyproject.toml

      - name: Install the project
        run: uv sync --extra docs --extra all

      - name: Documentation dependencies
        working-directory: python
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
          sudo apt install -y graphviz


      - name: Build Python documentation
        working-directory: python/docs
        run: make html
